version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: pagar-me_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pagar-me_app
    command: yarn dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DATABASE}?schema=public

volumes:
  pgdata:
    driver: local